# This file was generated by GoReleaser. DO NOT EDIT.
cask "bfm" do
  name "bfm"
  desc "BfM - Backend for Migrations CLI"
  homepage "https://github.com/toolsascode/bfm"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bfm"

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_darwin_amd64.tar.gz"
      sha256 "b0fe36daf374545301e29f57eae0c8958ecdb4e8d2415f593af8f604b3faa220"
    end
    on_arm do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_darwin_arm64.tar.gz"
      sha256 "7c4b5da023819fa6594103845d0502ff796c72a6fcd18e19bee5dbc6f9a38e5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_linux_amd64.tar.gz"
      sha256 "d038e23b4844e8e73105bedafe493218a6e58d16966df568b014befd7cbf80c5"
    end
    on_arm do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_linux_arm64.tar.gz"
      sha256 "81b1bb6c2feffc32215ee710f66a6d5fb68d474237a9d7a5b9e775d1097986c7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bfm"]
    end
  end

  # No zap stanza required
end
