# This file was generated by GoReleaser. DO NOT EDIT.
cask "bfm" do
  name "bfm"
  desc "BfM - Backend for Migrations CLI"
  homepage "https://github.com/toolsascode/bfm"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bfm"

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_darwin_amd64.tar.gz"
      sha256 "b017d78484653c19e21db30c003a7b47211d195e5cc0f081d66fbf50f544e40a"
    end
    on_arm do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_darwin_arm64.tar.gz"
      sha256 "a827743e284e41c898ee26c59e4ac2e4b2838bb36935466af5c0e867e4065e0b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_linux_amd64.tar.gz"
      sha256 "7e1e3a1d90fcf8782d804a996f69ae9898e005a6c2447d03a5be7b6ef473733d"
    end
    on_arm do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_linux_arm64.tar.gz"
      sha256 "ea861b0c56be95ee5fe62219b30f9ec666b058462c3945d58c2b6034ce85df3f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bfm"]
    end
  end

  # No zap stanza required
end
