# This file was generated by GoReleaser. DO NOT EDIT.
cask "bfm" do
  name "bfm"
  desc "BfM - Backend for Migrations CLI"
  homepage "https://github.com/toolsascode/bfm"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bfm"

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_darwin_amd64.tar.gz"
      sha256 "e01f7bb2f8fd85f090ed7a7d2bcee1155ea2f340944b7977bd80a585ac7fbee9"
    end
    on_arm do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_darwin_arm64.tar.gz"
      sha256 "07d5ede7d5ed48a108289bac5b1c79dc9b8bc81336c902cfd316a7454f83c9b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_linux_amd64.tar.gz"
      sha256 "79d9ceeae223c1b014c62ae629e14b23ac00f5b40b5ce353d96b05324d84b1aa"
    end
    on_arm do
      url "https://github.com/toolsascode/bfm/releases/download/v#{version}/bfm_#{version}_linux_arm64.tar.gz"
      sha256 "79cf6a4fefbc1b22099b6d6ab9deaa93f43dd84dba664820367435e4cf240898"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bfm"]
    end
  end

  # No zap stanza required
end
