# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodeler < Formula
  desc "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
  homepage "https://github.com/toolsascode/gomodeler"
  version "0.1.0-beta.1"
  license "Apache License 2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0-beta.1/gomodeler_Darwin_x86_64.tar.gz"
      sha256 "21b572a3a9a10aed7ede04e4cb76b25c945b82b86eb7fb090af47359c0165f0f"

      def install
        bin.install "gomodeler"
        bash_completion.install "completions/gomodeler.bash" => "gomodeler"
        zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
        fish_completion.install "completions/gomodeler.fish"
        man1.install "manpages/gomodeler.1.gz"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0-beta.1/gomodeler_Darwin_arm64.tar.gz"
      sha256 "f7ed0601e69d5ad684642ff4102a4b948a4d65ff00f3de11aaa02a985233f927"

      def install
        bin.install "gomodeler"
        bash_completion.install "completions/gomodeler.bash" => "gomodeler"
        zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
        fish_completion.install "completions/gomodeler.fish"
        man1.install "manpages/gomodeler.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0-beta.1/gomodeler_Linux_x86_64.tar.gz"
        sha256 "5e628c9a0fe8ab79db255d5ada3eeaa053205c2f6a39b68f6015abac60e5a910"

        def install
          bin.install "gomodeler"
          bash_completion.install "completions/gomodeler.bash" => "gomodeler"
          zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
          fish_completion.install "completions/gomodeler.fish"
          man1.install "manpages/gomodeler.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0-beta.1/gomodeler_Linux_arm64.tar.gz"
        sha256 "370847f4d15d3b77f67f7d2d030f31e3490062f25fc94feeb8801237873d08a3"

        def install
          bin.install "gomodeler"
          bash_completion.install "completions/gomodeler.bash" => "gomodeler"
          zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
          fish_completion.install "completions/gomodeler.fish"
          man1.install "manpages/gomodeler.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/gomodeler version"
  end
end
