# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodeler < Formula
  desc "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
  homepage "https://github.com/toolsascode/gomodeler"
  version "0.1.3"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.3/gomodeler_Darwin_x86_64.tar.gz"
      sha256 "0e934c2769d5891a9765b9b3207aa67005073f68385318ced88479b21f66d2bc"

      def install
        bin.install "gomodeler"
        bash_completion.install "completions/gomodeler.bash" => "gomodeler"
        zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
        fish_completion.install "completions/gomodeler.fish"
        man1.install "manpages/gomodeler.1.gz"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.3/gomodeler_Darwin_arm64.tar.gz"
      sha256 "0a7710da62597b585c1da7bb254f6e83ee0e5853e8e138bd78faccda54ccea5d"

      def install
        bin.install "gomodeler"
        bash_completion.install "completions/gomodeler.bash" => "gomodeler"
        zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
        fish_completion.install "completions/gomodeler.fish"
        man1.install "manpages/gomodeler.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.3/gomodeler_Linux_x86_64.tar.gz"
        sha256 "4629bd9174ad49f2916725eed37b5fbe6ace73c875e881de0266f4ccfced1e4b"

        def install
          bin.install "gomodeler"
          bash_completion.install "completions/gomodeler.bash" => "gomodeler"
          zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
          fish_completion.install "completions/gomodeler.fish"
          man1.install "manpages/gomodeler.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.3/gomodeler_Linux_arm64.tar.gz"
        sha256 "5ef1847a19bf6031cf5b05323eb7a674c6e75eacb7e6bc112404e66fe1a9425c"

        def install
          bin.install "gomodeler"
          bash_completion.install "completions/gomodeler.bash" => "gomodeler"
          zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
          fish_completion.install "completions/gomodeler.fish"
          man1.install "manpages/gomodeler.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/gomodeler version"
  end
end
