# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodeler < Formula
  desc "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
  homepage "https://github.com/toolsascode/gomodeler"
  version "0.1.0"
  license "Apache License 2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0/gomodeler_Darwin_x86_64.tar.gz"
      sha256 "9bffdd04f2788ed43986f06af1783ecc8164d3f3c0aad9678ba1547082212670"

      def install
        bin.install "gomodeler"
        bash_completion.install "completions/gomodeler.bash" => "gomodeler"
        zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
        fish_completion.install "completions/gomodeler.fish"
        man1.install "manpages/gomodeler.1.gz"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0/gomodeler_Darwin_arm64.tar.gz"
      sha256 "1958ef6bf0c76e72c0ab10874a75b5b4b66caa1bc639e7afb16209aaaa98ddf9"

      def install
        bin.install "gomodeler"
        bash_completion.install "completions/gomodeler.bash" => "gomodeler"
        zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
        fish_completion.install "completions/gomodeler.fish"
        man1.install "manpages/gomodeler.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0/gomodeler_Linux_x86_64.tar.gz"
        sha256 "9dca84c04c715e7c4a3bb3501019295d90bd44c821a699d3aec2c47e44d8ac21"

        def install
          bin.install "gomodeler"
          bash_completion.install "completions/gomodeler.bash" => "gomodeler"
          zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
          fish_completion.install "completions/gomodeler.fish"
          man1.install "manpages/gomodeler.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/gomodeler/releases/download/v0.1.0/gomodeler_Linux_arm64.tar.gz"
        sha256 "54dddfb9202a0b31caaece642756a6b2cc8acf5014e35ca0b6c78f88a2e8eac4"

        def install
          bin.install "gomodeler"
          bash_completion.install "completions/gomodeler.bash" => "gomodeler"
          zsh_completion.install "completions/gomodeler.zsh" => "_gomodeler"
          fish_completion.install "completions/gomodeler.fish"
          man1.install "manpages/gomodeler.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/gomodeler version"
  end
end
