# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmS3Publisher < Formula
  desc "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
  homepage "https://github.com/toolsascode/helm-s3-publisher"
  version "1.0.1"
  license "Apache License 2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.1/helm-s3-publisher_Darwin_x86_64.tar.gz"
      sha256 "3e62d0cbd6d41b5420f98a1e81f2fead4a333ba09852265bbc2aff3768ddfbde"

      def install
        bin.install "helm-s3-publisher"
        bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
        zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
        fish_completion.install "completions/helm-s3-publisher.fish"
        man1.install "manpages/helm-s3-publisher.1.gz"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.1/helm-s3-publisher_Darwin_arm64.tar.gz"
      sha256 "997fc46759a4d68b09c92b82f65ceab37f5cb41a89e044c12d65b8e4328f7fd4"

      def install
        bin.install "helm-s3-publisher"
        bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
        zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
        fish_completion.install "completions/helm-s3-publisher.fish"
        man1.install "manpages/helm-s3-publisher.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.1/helm-s3-publisher_Linux_x86_64.tar.gz"
        sha256 "e6e8d702487f009274d727aea9b0dd4026778eb49a502bd0871669e9d0528204"

        def install
          bin.install "helm-s3-publisher"
          bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
          zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
          fish_completion.install "completions/helm-s3-publisher.fish"
          man1.install "manpages/helm-s3-publisher.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.1/helm-s3-publisher_Linux_arm64.tar.gz"
        sha256 "c45392507196a8db7746bddf0331147032ca621224c4823393a2b8a2fad80f84"

        def install
          bin.install "helm-s3-publisher"
          bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
          zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
          fish_completion.install "completions/helm-s3-publisher.fish"
          man1.install "manpages/helm-s3-publisher.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/helm-s3-publisher version"
  end
end
