# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmS3Publisher < Formula
  desc "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
  homepage "https://github.com/toolsascode/helm-s3-publisher"
  version "1.0.0"
  license "Apache License 2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Darwin_x86_64.tar.gz"
      sha256 "e388f089b1c2dbf1269f4eb22ae4165067dfed73578a966b5f4a64e01fa3a292"

      def install
        bin.install "helm-s3-publisher"
        bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
        zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
        fish_completion.install "completions/helm-s3-publisher.fish"
        man1.install "manpages/helm-s3-publisher.1.gz"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Darwin_arm64.tar.gz"
      sha256 "3283925de42b9a688b05027a27ce4680922ab8506a00730b63dd9e412c528ded"

      def install
        bin.install "helm-s3-publisher"
        bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
        zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
        fish_completion.install "completions/helm-s3-publisher.fish"
        man1.install "manpages/helm-s3-publisher.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Linux_x86_64.tar.gz"
        sha256 "4c37f53fd0f5bbc8427491833f385124c77733762ec74c83e38436be9f91f03e"

        def install
          bin.install "helm-s3-publisher"
          bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
          zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
          fish_completion.install "completions/helm-s3-publisher.fish"
          man1.install "manpages/helm-s3-publisher.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Linux_arm64.tar.gz"
        sha256 "09b1d08ec311bdd901ab19f7062f68f3109c993e50f5b1abef19a4fb33b18f3f"

        def install
          bin.install "helm-s3-publisher"
          bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
          zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
          fish_completion.install "completions/helm-s3-publisher.fish"
          man1.install "manpages/helm-s3-publisher.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/helm-s3-publisher version"
  end
end
