# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmS3Publisher < Formula
  desc "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
  homepage "https://github.com/toolsascode/helm-s3-publisher"
  version "1.0.0"
  license "Apache License 2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Darwin_x86_64.tar.gz"
      sha256 "338ea1a2384defe9f15f27d9125fb32caf059d1585f7e18e17def8f052daaf8c"

      def install
        bin.install "helm-s3-publisher"
        bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
        zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
        fish_completion.install "completions/helm-s3-publisher.fish"
        man1.install "manpages/helm-s3-publisher.1.gz"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Darwin_arm64.tar.gz"
      sha256 "8455b3a893aa506844bfc55eeeb51595dd91790a32a1e334d876129c34d2458f"

      def install
        bin.install "helm-s3-publisher"
        bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
        zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
        fish_completion.install "completions/helm-s3-publisher.fish"
        man1.install "manpages/helm-s3-publisher.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Linux_x86_64.tar.gz"
        sha256 "be3b6eb743c1b48d91f15318056482ef5e5ea8b45a3ca79372ee524b218122ed"

        def install
          bin.install "helm-s3-publisher"
          bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
          zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
          fish_completion.install "completions/helm-s3-publisher.fish"
          man1.install "manpages/helm-s3-publisher.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/helm-s3-publisher/releases/download/v1.0.0/helm-s3-publisher_Linux_arm64.tar.gz"
        sha256 "e0cfdcef9cbc2e55b33b2b06368ad6709e00dd99c5dac34dea10d2ce6e9b94e8"

        def install
          bin.install "helm-s3-publisher"
          bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
          zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
          fish_completion.install "completions/helm-s3-publisher.fish"
          man1.install "manpages/helm-s3-publisher.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/helm-s3-publisher version"
  end
end
